////////////////////////////////////////////////////////////////////////////////
//
//  ALLJOYN MODELING TOOL - GENERATED CODE
//
//  This is an autogenerated or copied file which Qualcomm Innovation Center,
//  Inc., as author hereby dedicates to the public domain.  Additionally, THIS
//  SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND ANY CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
//  AND OF GOOD TITLE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
//  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
//  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
//  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
//  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
//  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
////////////////////////////////////////////////////////////////////////////////
//
//  DO NOT EDIT
//
//  Add a category or subclass in separate .h/.m files to extend these classes
//
////////////////////////////////////////////////////////////////////////////////
//
//  PGMTestObjectImpl.h
//
////////////////////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import "AllJoynFramework/AJNBusAttachment.h"
#import "AllJoynFramework/AJNBusInterface.h"
#import "AllJoynFramework/AJNProxyBusObject.h"


////////////////////////////////////////////////////////////////////////////////
//
// Session mapping blocks
//
typedef AJNSessionId(^GroupNameToSessionId)(NSString *string);
typedef NSString *(^SessionIdToGroupName)(AJNSessionId sessionId);
////////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////////
//
// TestDelegate Bus Interface
//
////////////////////////////////////////////////////////////////////////////////

@protocol TestDelegate <AJNBusInterface>


// methods
//
- (NSString*)echoString:(NSString*)str fromSender:(NSString *)sender;


@end

////////////////////////////////////////////////////////////////////////////////

    

////////////////////////////////////////////////////////////////////////////////
//
//  AJNTestObject Bus Object superclass
//
////////////////////////////////////////////////////////////////////////////////

@interface AJNTestObject : AJNBusObject<TestDelegate>

// properties
//


// methods
//
- (NSString*)echoString:(NSString*)str fromSender:(NSString *)sender;


// signals
//


// signal handler registration
//

                
// session mapping blocks
//
@property (nonatomic, strong) GroupNameToSessionId sessionIdLookup;
@property (nonatomic, strong) SessionIdToGroupName groupNameLookup;

- (QStatus)registerInterfacesWithBus:(AJNBusAttachment *)busAttachment;

@end

////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//
//  TestObject Proxy
//
////////////////////////////////////////////////////////////////////////////////

@interface TestObjectProxy : AJNProxyBusObject

// properties
//


// methods
//
- (NSString*)echoString:(NSString*)str;


@end

////////////////////////////////////////////////////////////////////////////////
